### ISSUE TITLE
q-for quit versus tags

### ISSUE THREAD

**Issue by PBorocz** [sheijk/org-menu#1]
The default key-bindings for less-often used org commands can be inscrutable and the transient interface is perfect for presenting them!

Only thought after a few days of using it is how to add consistency with magit and use 'q' to quit instead of ctrl-g. I continually expect 'q' to quit a transient interface (thank you magit!)

Now that I look at the repo, the screenshot: org-menu-headline.png that's there **perfectly** captures this! ('T' for tags and q for quit); Why the change? Any way to get that back??

Thanks for your work on this, great addition to the org-environment!

**Comment by sheijk** [comment]
I changed this because C-q already can be used to quit everywhere and this freed the "q" binding to be used. I'm trying to have key bindings consistent with default org-mode bindings so this is more useful as an explorative learning tool. Also the quit action adds another column to an interface already tricky with small screens.

But the missing "q" for quit also confuses me from time to time. So maybe using "Q" for tags/cancelling timers makes sense? Or a user option? I'm not sure so I'd be happy for some feedback on this and what user expect.

**Comment by PBorocz** [comment]
I see the goal as a great learning tool, however, this is a unique opportunity to teach the display & use _functionality_ of org instead of tracking down anachronistic keyboard mappings (heck, C-c , for org-priority? after many many years, it's still not baked into my fingers!)

--> I hadn't thought about the "Q" idea **but I like it**...that doesn't stray too far from the uppercase 'P' and 'A' that are already in use. I don't think the user option is worth the work (until more feedback justifies it).

p.s.
Funny that I gave the org-priority example, I don't see org-priority in org-menu.el ;-)

**Comment by sheijk** [comment]
I've added an experimental version of this in feature/option-q-for-quit. Customize org-menu-use-q-for-quit to toggle it

**Comment by sheijk** [comment]
Support for org-priority has been added in cf23fbb76ce31089e9a7b669c97dcb9d5b252ad4 yesterday. But is does use "," as a binding, of course :)

**Comment by PBorocz** [comment]
Thanks Jan, after a few hours using it this morning, org-menu-use-q-for-quit works great! No break in work flow with the 'q' and 'Q' works _fine_  for tags after only a few half-second glances down to the menu. 

I can't see any reason why anyone else wouldn't like the ability to have either "pure" org mappings or _slightly_ updated ones for consistency with other transient mini-buffers.

Feel free to close and thank you!!

(and thanks for org-priority ;-)

**Comment by sheijk** [comment]
Merged this into main, changing the default to be enabled as I think that's what most users familiar with Magit expect
