### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sakagsakag** [sheijk/org-menu#2]
condition-case: Symbol’s value as variable is void: org-link-bracket-re

**Comment by sheijk** [comment]
Could you provide the output of `M-x emacs-version` and `M-x org-version`?

**Comment by sakagsakag** [comment]
sorry, lack of info.

GNU Emacs 26.1 (build 2, arm-unknown-linux-gnueabihf, GTK+ Version 3.24.5) of 2021-02-07, modified by Debian

Org mode version 9.1.14 (9.1.14-dist @ /usr/share/emacs/site-lisp/elpa/org-9.1.14/)

raspberrypi os 
raspberry pi 3b+

**Comment by sheijk** [comment]
Should be fixed with revision c9f50e6. At least opening the menu and running common operations works but there might be other issues lurking. Tested on Emacs 26.3, org-mode 9.1.9 from Nix (nix-shell -p emacs26 on NixOs)

**Comment by sakagsakag** [comment]
thanks for update, but another error 
"condition-case: Symbol’s value as variable is void: org-link-angle-re"

**Comment by sakagsakag** [comment]
org-menu.el

line no.447  (org-in-regexp org-angle-link-re 1)
           448  (org-in-regexp org-plain-link-re 1)))
           700 ;;  ("C-c C-c" "confirm capture" org-capture-finalize :if-non-nil org-capture-mode)
           701 ;;  ("C-c C-k" "abort capture" org-capture-kill :if-non-nil org-capture-mode)



and it works.  i dont know e-lisp well, so line no.700 and 701 are only comment outed.

**Comment by sheijk** [comment]
Thanks, that's very helpful. I've pushed a new version guarding against these errors

**Comment by sakagsakag** [comment]
now your code work fine. thank you all your effort.
