### ISSUE TITLE
Submit to ELPA/MELPA/Org-upstream?

### ISSUE THREAD

**Issue by minad** [sheijk/org-menu#3]

**Comment by sheijk** [comment]
That's a good idea and I plan to do this in the end. However for now I still see this as a bit experimental and I haven't heard much feedback from users so I'm not sure this is ready to be submitted, yet

**Comment by minad** [comment]
From what I've seen, I think it is ready :)

**Comment by Boruch-Baum** [comment]
I support you applying to melpa and am willing to help you with the application if you need any help.

**Comment by sheijk** [comment]
@Boruch-Baum thanks. I think I've checked most things required by Melpa. What stopped me from submitting was that I'm not entirely sure I'm using transient in an optimal way. See some of the quasi-quotations I need to produce the menu. I have a vague feeling there might be better ways to do this but couldn't figure them out using other projects and the existing docs. And as far as I see it's author is working on more documentation but also very busy. So a review of transient usage here would help me if you're familiar with it

**Comment by Boruch-Baum** [comment]
On 2022-02-13 10:19, Jan R wrote:
> So a review of transient usage here would help me if you're familiar
> with it

Sorry. I'm clueless about that package's internals. My feeling is that
your package needn't be perfect, and that it already will be found
useful to many users. Publishing it on MELPA will make it more
discoverable to more users, each of whom is a potential collaborator and
contributor to help you improve the package. Also, @Tarsius, the
developer of the transient package, is active presence on the MELPA
project, so the simple act of applying to MELPA is bound to get his
attention. (Oops. By mentioning him on-list by his github '@' name, I
many have attracted his attention for you regardless...)

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by minad** [comment]
Would it make sense to rename this package to `org-transient` before submission to a package repository?

**Comment by Boruch-Baum** [comment]
On 2022-02-13 11:20, Daniel Mendler wrote:
>    Would it make sense to rename this package to org-transient before
>    submission to a package repository?

Ha! You are asking the correct person! I had the same question about one
of my packages just a few months ago. What I think I did was submit it
to melpa, and as part of the submission (ie, the github "issue" to add
the recipe), I raised my ambivalence about my choice of name-space and
solicited suggestions (Hmm. My memory isn't great about this. Maybe what
I did was submit an issue about my naming convention... not a big
difference IMO). They gave me great feedback that I adopted. Keep
in mind that your request doesn't generate an accept/reject response:
expect a code-review and a possible discussion. Some packages go through
many git commits between submission and acceptance. That's just more
opportunities for you to get constructive input from experienced elisp
developers.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by Boruch-Baum** [comment]
On 2022-02-13 11:20, Daniel Mendler wrote:
>    Would it make sense to rename this package to org-transient before
>    submission to a package repository?

I like org-transient better than org-menu, but do see my previous
message, and do get feedback from more people than just me.

Also, consider that even without MELPA, your package has collected 50
github stars, so you have followers whom can be asked. They'll also
probably be interested in finding out if the project becomes melpa-fied.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by tarsius** [comment]
I've been summoned? :smiling_imp: 

> Also, [@tarsius](https://github.com/tarsius), the developer of the transient package, is active presence on the MELPA project, so the simple act of applying to MELPA is bound to get his attention.

Maybe, maybe not. To be sure you got to mention me explicitly.

I haven't looked to closely at this package yet, but am happy someone else wrote it so that I don't have to. :grinning: 

Also there's a bit of talk about using transient on the org-list: https://list.orgmode.org/20220207153704.104259-1-mejlaandersj@gmail.com/T/#t. I haven't joined in and don't plan to review this in depth anytime soon because my plan is to work on transient in April and focus on other things before then.

**Comment by sheijk** [comment]
For the name: I consider using transient an implementation detail, it could as well use hydra. Although realistically switching might break configs and extensions if someone makes one in the future

Thanks for the link to the orgmode discussion, will look into it

**Comment by sheijk** [comment]
@tarsius if I condense the places where I'm not sure about my usage of transient APIs into small examples would you be able to provide feedback (as in "this feature would make this simpler")?

**Comment by minad** [comment]
> For the name: I consider using transient an implementation detail, it could as well use hydra. Although realistically switching might break configs and extensions if someone makes one in the future

Yes, one could consider it a detail. However Transient is part of Emacs now and people may prefer to either use Hydra or Transient for consistency, since these packages overlap too much. Therefore it may be an advantage to be explicit here. Since Transient made it into Emacs, I assume it will be the go-to libray for new packages. On the other hand org-menu is a shorter and snappier name. I don't have a strong opinion.

**Comment by tarsius** [comment]
@sheijk Yes, but I might be slow and would appreciate it if you first searched to see if others already made similar feature requests.

**Comment by tarsius** [comment]
Hm, that might have come out too negative.

Hearing from people who want to do things with `transient` that seem just in reach but aren't quite there yet is useful.

**Comment by floli** [comment]
Hey there! Sorry to warm up this closed issue. It was originally about MELPA inclusion. Is the package now available from MELPA? I wasn't able to find it, maybe under a different name?
