### ISSUE TITLE
Make yasnippet dependency optional or depend on yasnippet

### ISSUE THREAD

**Issue by minad** [sheijk/org-menu#4]
I would prefer if the dependency is optional. If yasnippet is available, you could use it, if not just insert the placeholder text without expansion, e.g., "a^b".

**Comment by sheijk** [comment]
Commit 466cc43 tries to do this. Could you try and see if this works for you?

**Comment by minad** [comment]
There are two more yas calls:

https://github.com/sheijk/org-menu/blob/466cc438add6d7ee2cdb0f58b27744e197624656/org-menu.el#L242-L245

Furthermore if you implement it like this, you have to make sure that the bytecode compiler does not complain by using `declare-function`. Ideally I would like to have an implementation like this, such that the functionality degrades gracefully if yasnippet is not available.

~~~ elisp
(defun org-menu-insert-superscript ()
  "Insert a text with superscript."
  (interactive)
  (if (require 'yasnippet nil 'noerror)
    (yas-expand-snippet "${1:text}^{${2:super}}")
   (insert "a^b")))
~~~

But it is a matter of preference. You can also decide to create a hard dependency of your package to yasnippet or accept that the yasnippet-dependent commands fail if yasnippet is not available.

**Comment by sheijk** [comment]
All uses should be fixed now. Does it work for you?

**Comment by minad** [comment]
Yes, thanks!

**Comment by minad** [comment]
Hey, I recently developed [Tempel](https://github.com/minad/tempel), so I wonder if there is interest in supporting different template packages in org-menu in addition to yasnippet? One could either check for the template packages via fbound or introduce an template-expand-function defcustom, which will then take a template key as argument.

**Comment by sheijk** [comment]
Yes, I'm very open to that. When I added yasnippet support I thought it had been moved into Emacs core. Otherwise this would be some form of extension. I'm haven't spent time to consider how to best do this for every use of yasnippet, yet. If you have ideas I'd be happy to hear them. Ideally it would be more or less automatic

**Comment by sheijk** [comment]
Oh, and feel free to open a new issue for this. Comments here will be hard to find as the closed issue is not shown by default
