### ISSUE TITLE
Compilation problem in doom emacs

### ISSUE THREAD

**Issue by johanwiden** [sheijk/org-menu#5]
I am using doom emacs with emacs version 28 pretest, and native compilation.
When I added org-menu to packages.el in doom emacs:
  (package! org-menu
    :recipe (:host github :repo "sheijk/org-menu"))
and the executed "doom sync" from the command line, it failed with error message that 
  transient-define-prefix
was undefined. I compared the code in org-menu.el to the one in magit.el, and found that the autoload directives look different in magit.el: They include an s-expression for the autoload, thus defining the name for autoload.
So I have cloned the org-menu-repo and changed the autoload directives like this:
From:
;;;###autoload
To:
;;;###autoload (autoload 'org-menu-visibility "org-menu" nil t)

I can now use org-menu in my doom emacs.

**Comment by sheijk** [comment]
Thanks, merged your fix
