### ISSUE TITLE
The noop line breaks the whole transient prefix

### ISSUE THREAD

**Issue by astynax** [sheijk/org-menu#9]
Hi! [This line](https://github.com/sheijk/org-menu/blob/d7d2f2132f87afb80dc12969c50aeb19ccdf9384/org-menu.el#L1014) somehow breaks `(transient-setup)` on my machine with a fresh version of transient package. Currently, I have transient-20240509 installed but the problem appeared quite earlier, because I tried to solve it with upgrading of the transient package. For now I commented out that line and now org-menu works for me.

**Comment by sheijk** [comment]
Looks like the way I created an empty line was invalid and only worked by chance in earlier versions. Fixed, thanks for reporting
